CREATE TABLE USERS(
    USERNAME VARCHAR2(50) NOT NULL PRIMARY KEY,
    PASSWORD VARCHAR2(50) NOT NULL,
    ENABLED CHAR(1) DEFAULT '1'
);

CREATE TABLE AUTHORITIES(
    USERNAME VARCHAR2(50) NOT NULL,
    AUTHORITY VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_AUTHORITIES_USERS FOREIGN KEY(USERNAME) 
    REFERENCES USERS(USERNAME)
);

CREATE UNIQUE INDEX IX_AUTH_USERNAME ON AUTHORITIES(USERNAME, AUTHORITY);

INSERT INTO USERS (USERNAME, PASSWORD) VALUES('user00', 'user00');
INSERT INTO USERS (USERNAME, PASSWORD) VALUES('commi', 'commi');
INSERT INTO USERS (USERNAME, PASSWORD) VALUES('member00', 'member00');
INSERT INTO USERS (USERNAME, PASSWORD) VALUES('admin00', 'admin00');

INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('user00','ROLE_USER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('commi','ROLE_USER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('member00', 'ROLE_MANAGER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('admin00', 'ROLE_MANAGER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('admin00', 'ROLE_ADMIN');
COMMIT;

-- 인증 / 권한을 위한 테이블 설계
CREATE TABLE TBL_MEMBER (
    USERID VARCHAR2(50) NOT NULL PRIMARY KEY,
    USERPW VARCHAR2(100) NOT NULL,
    USERNAME VARCHAR2(100) NOT NULL,
    REGDATE DATE DEFAULT SYSDATE,
    UPDATEDATE DATE DEFAULT SYSDATE,
    ENABLED CHAR(1) DEFAULT '1'
);

CREATE TABLE TBL_MEMBER_AUTH (
    USERID VARCHAR2(50) NOT NULL,
    AUTH VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_MEMBER_AUTH FOREIGN KEY(USERID) 
    REFERENCES TBL_MEMBER(USERID)
);
